### PR TITLE
Do not run TastyPostProcessor for snapshot compilers

### LINKED ISSUE #232: TASTy version should depend on the Scala version
Scala 3.1.0 has a new TASTy version, however this makes using scala-cli unusable for 3.1.0 as it is hard coded to expect the same tasty version as Scala 3.0.0 (i.e. 28.0-0)

here is a good test file: (run with `scala-cli -S 3.1.0 tastyVersion.sc`)
```scala
import dotty.tools.tasty.TastyFormat.*

val isPreview =
  if ExperimentalVersion > 0 then
    s" (preview $ExperimentalVersion)"
  else
    ""

val tastyVersion = s"$MajorVersion.$MinorVersion$isPreview"

println(s"TASTy version is $tastyVersion")

```

currently the renaming step causes a crash due to unexpected TASTy:
```scala
Compiling project (Scala 3.1.0, JVM)
Compiled project (Scala 3.1.0, JVM)
Exception in thread "main" scala.build.tastylib.UnpickleException: TASTy signature has wrong version.
 expected: {majorVersion: 28, minorVersion: 0}
 found   : {majorVersion: 28, minorVersion: 1}

This TASTy file was produced by a more recent, forwards incompatible release.
To read this TASTy file, please upgrade your tooling.
The TASTy file was produced by Scala 3.1.0.
```

### PR DESCRIPTION
**Pull request by tpasternak**
Fixes #232

### CODE REVIEW

**Comment by alexarchambault** [comment]
@tpasternak What's the problem with tasty post-processing and snapshot compilers?

**Comment by tpasternak** [comment]
In general builds just fail for snapshot compilers now, because scalac experimental version number is always wrong. (in TastyFormat.scala file). It's the issue described in #232

We could ignore this check for snapshot builds, but IMO it would be better to just disable the postprocessor in this case, because it's not that uncommon to change tasty format if changing the compiler code.

If you think it would be better to just ignore the check, then I'm ok with it.

**Comment by alexarchambault** [comment]
Maybe we could just add options to disable some post-processing steps then, as you suggested elsewhere. (And tasty post-processing could be disabled by default for snapshot compilers via these options' defaults.)

These options could be useful even for non-snapshot future Scala 3 versions for example.

**Comment by alexarchambault** [comment]
About disabling the tasty version check, I've been wanting to do something along those lines some time ago IIRC.

Actually, I just found the local branch where I've been doing that, simplifying the `tasty-lib` module along the way. I'm going to try to open a PR with that. But options to disable some post-processing steps would definitely be useful too.

**Pull request closed without merging**
