### PR TITLE
Allow custom repositories for scala-library in repl

### LINKED ISSUE #107: Support running Scala 2 nightlies (and PR validation snapshots)
I had hoped this might work:

    scala-cli repl --scala 2.13.7-bin-072e68e

and I also thought it might work if I used `--repository`:

    scala-cli repl --scala 2.13.7-bin-072e68e \
      --repository https://scala-ci.typesafe.com/artifactory/scala-integration/

but it seems that `--repository` isn't used when resolving Scala itself:

```
Exception in thread "main" java.lang.Exception: coursier.error.ResolutionError$Several: Error downloading org.scala-lang:scala-library:2.13.7-bin-072e68e
  not found: /Users/tisue/.ivy2/local/org.scala-lang/scala-library/2.13.7-bin-072e68e/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.7-bin-072e68e/scala-library-2.13.7-bin-072e68e.pom
  not found: /Users/tisue/Library/Caches/ScalaCli/local-repo/latest-384-1cf98a/org.scala-lang/scala-library/2.13.7-bin-072e68e/ivys/ivy.xml
```

It would also be nice if Scala PR validation snapshots were also supported; those come from https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots . For convenience ,[scala-runners](https://github.com/dwijnand/scala-runners) allows `--scala-pr 8960` and figures out the version number.

### PR DESCRIPTION
**Pull request by tpasternak**
It is now possible to run `scala-cli -S 2.13.8-foobar --repository https://<some_repo>`

closes #107

### CODE REVIEW

**Review by romanowski — APPROVED** [review]

**Comment by SethTisue** [comment]
nice!! thanks!

**Comment by SethTisue** [comment]
I've added this to https://stackoverflow.com/questions/40622878/how-do-i-tell-sbt-or-scala-cli-to-use-a-nightly-build-of-scala-2-12-or-2-13

**Comment by SethTisue** [comment]
I'm trying to use this to run a Scala 2 PR validation snapshot:

```
% scala-cli -version
Scala CLI version: 0.1.18
Scala version (default): 3.2.1
% scala-cli repl --repository https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots \
  -S 2.13.11-bin-89f3de5-SNAPSHOT
```

but it fails:

```
[error]  Cannot find matching Scala version for '2.13.11-bin-89f3de5-SNAPSHOT'
You can only choose one of the 3.x, 2.13.x, and 2.12.x. versions.
The latest supported stable versions are 3.2.0, 2.13.10, 2.12.17.
In addition, you can request compilation with the last nightly versions of Scala,
by passing the 2.nightly, 2.12.nightly, 2.13.nightly, or 3.nightly arguments.
Specific Scala 2 or Scala 3 nightly versions are also accepted.
```

in sbt, the same thing succeeds; with this `build.sbt` I can run `sbt console`:

```
ThisBuild / resolvers +=
  "prs" at "https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots"
scalaVersion := "2.13.11-bin-89f3de5-SNAPSHOT"
```

**Comment by lwronski** [comment]
> I'm trying to use this to run a Scala 2 PR validation snapshot:
> 
> ```
> % scala-cli -version
> Scala CLI version: 0.1.18
> Scala version (default): 3.2.1
> % scala-cli repl --repository https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots \
>   -S 2.13.11-bin-89f3de5-SNAPSHOT
> ```
> 
> but it fails:
> 
> ```
> [error]  Cannot find matching Scala version for '2.13.11-bin-89f3de5-SNAPSHOT'
> You can only choose one of the 3.x, 2.13.x, and 2.12.x. versions.
> The latest supported stable versions are 3.2.0, 2.13.10, 2.12.17.
> In addition, you can request compilation with the last nightly versions of Scala,
> by passing the 2.nightly, 2.12.nightly, 2.13.nightly, or 3.nightly arguments.
> Specific Scala 2 or Scala 3 nightly versions are also accepted.
> ```
> 
> in sbt, the same thing succeeds; with this `build.sbt` I can run `sbt console`:
> 
> ```
> ThisBuild / resolvers +=
>   "prs" at "https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots"
> scalaVersion := "2.13.11-bin-89f3de5-SNAPSHOT"
> ```

@SethTisue  Thanks for reporting, it should be fixed by https://github.com/VirtusLab/scala-cli/pull/1630/. Thanks for finding the bug, unfortunately there is no workaround now.

**Pull request merged**
