### PR TITLE
Make --python and --spark work fine alongside each other

### PR DESCRIPTION
**Pull request by alexarchambault**

### CODE REVIEW

**Comment by alexarchambault** [comment]
Includes https://github.com/VirtusLab/scala-cli/pull/1531 for now.

**Comment by alexarchambault** [comment]
(These were the last bits of https://github.com/VirtusLab/scala-cli/pull/1270.)

**Comment by alexarchambault** [comment]
(Current first commit https://github.com/VirtusLab/scala-cli/pull/1594/commits/4b6a3c7b37fa5d7a49492bd7a10e387a60bc6a18 doesn't do what its messages says it does, not sure what happened here…)

**Comment by Gedochao** [comment]
Closing this for now, @alexarchambault feel free to reopen if you continue working on it.

**Pull request closed without merging**
