### PR TITLE
refactor: Switch to original fork of Bloop

### PR DESCRIPTION
**Pull request by tgodzik**

### CODE REVIEW

**Comment by tgodzik** [comment]
`2.0.0-RC1` is out, we should be good to merge this after the release.

**Comment by tgodzik** [comment]
Sonatype issues strike again :/

**Comment by tgodzik** [comment]
@Gedochao do I have your blessing to merge this? The Metals PR is done

**Comment by Gedochao** [comment]
> @Gedochao do I have your blessing to merge this? The Metals PR is done

You do, go ahead 😅

**Review by Gedochao — APPROVED** [review]

**Comment by Gedochao** [comment]
Ah, a rebase will be necessary, though.

**Comment by sideeffffect** [comment]
Huge congratulations and thanks for this achievement. Can we expect a new release of scala-cli with this anytime soon?

**Comment by Gedochao** [comment]
> Huge congratulations and thanks for this achievement. Can we expect a new release of scala-cli with this anytime soon?

Yes, the plan is to include it in the next release in ~2 weeks.
- https://github.com/VirtusLab/scala-cli/issues/3090

**Pull request merged**
