### PR TITLE
Fix scala-cli version used in our build

### PR DESCRIPTION
**Pull request by romanowski**

### CODE REVIEW

**Comment by alexarchambault** [comment]
Why not just disable the use of Scala CLI on Windows?

**Comment by romanowski** [comment]
It is not only Windows it also fails on Linux (my machine) and macs (Ina's). It is caused by the problem with handling multiple `-O` options

**Comment by alexarchambault** [comment]
A problem is that `--cli-version` makes us use the JVM version of Scala CLI, which is kind of slow.

**Comment by romanowski** [comment]
problem will be fixed in next release, we do not want to have it merged

**Pull request closed without merging**
