### PR TITLE
[ISSUE-296] Add support for fish autocompletions

### LINKED ISSUE #296: Fish shell completion support
from @alexarchambault 

For now, we only support bash and zsh completion. I'm not sure what is needed to have fish completion work.

Implementing this should mostly involve changes in [case-app](https://github.com/alexarchambault/case-app), where the core of bash and zsh completion support lives.

### PR DESCRIPTION
**Pull request by KristianLentino99**
Hi all, I wanted to contribute a little bit to this fantastic project so I've taken a look at your "Good first Issues" and I've decided to pick up [this one](https://github.com/VirtusLab/scala-cli/issues/296). 
- I've updated the related test and ran all the steps mentioned in the CONTRIBUTING guidelines. 
- I've also updated the Advanced installation doc adding the tab for the new `fish` CLI. 

I've also ran `scala-cli` with my changes locally and installed it from scratch  to test if it works:
image

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]
Thanks! I tested it out and look to work except when using completion without any input. That seems to be case app issue though and can be further improved.

**Comment by tgodzik** [comment]
Actually works fine, I had leftover code from a previous attempt. I wonder if we could get also next subcommands, it doesn't seem implemented in case app (or scala-cli?)

**Comment by tgodzik** [comment]
Ad 3. Looks like some subcommands work, while other do not (bloop about is not suggested). Anyway looks like we can improve things further, but this already works awesome!

**Comment by Gedochao** [comment]
> Ad 3. Looks like some subcommands work, while other do not (bloop about is not suggested). Anyway looks like we can improve things further, but this already works awesome!

@tgodzik Can you extract any issues you've found into separate issues?

**Review by Gedochao — APPROVED** [review]
Looks good, thanks for the contribution!

**Comment by tgodzik** [comment]
> > Ad 3. Looks like some subcommands work, while other do not (bloop about is not suggested). Anyway looks like we can improve things further, but this already works awesome!
> 
> @tgodzik Can you extract any issues you've found into separate issues?

Funny thing, those commands do not exist in Scala CLI codebase, but they work since they are just forwarded to Bloop, which understands more commands. The question is whether they should be showed by Scala CLI?

This is things like `scala bloop projects` or even `scala bloop compile` both of which will actually not work unless run in scala-build directory :sweat_smile: 

The only one I think we could add is `about`

**Pull request merged**
