### PR TITLE
Improve formatting of generated Mill project

### PR DESCRIPTION
**Pull request by lolgab**
Before this PR:
Before
After this PR:
After

### CODE REVIEW

**Comment by lwronski** [comment]
Hi @lolgab First of all, I would like to thank you for your contribution, it would be great to merge your changes. 

Maybe you need some help to finish this PR?

**Comment by lolgab** [comment]
Hi @lwronski,
I moved to other things and forgot about this PR, good that you asked.
I fixed the failing test, let's see if everything passes now :)

**Comment by lolgab** [comment]
@lwronski the test that's failing seems flaky. Do you want to retry the failing step?

**Comment by lwronski** [comment]
> @lwronski the test that's failing seems flaky. Do you want to retry the failing step?

Done.

**Review by lwronski — APPROVED** [review]
LGTM! Thanks for contribution.

**Pull request merged**
