### PR TITLE
implementing doctor diagnosis, common problems and print information

### PR DESCRIPTION
**Pull request by asjad02**
#698  WIP

cc @mtk

### CODE REVIEW

**Comment by mtk** [comment]
hmm... i'm confused.  i added your fork of VirtusLab/scala-cli as a remote to a new clone of VirtusLab/scala-cli (really a new worktree on an existing clone).  i did a 'git fetch <your-fork>' and then a 'git co -b asjad/issue-698-doctor-command-impl'.  i see Doctor.scala and DoctorOptions.scala in the file system.  but it does not have the version in your pull request but instead the earlier version?

**Comment by mtk** [comment]
or do you want to add me as a contributor to your fork.  i can add commits and you can generate pull requests for the master from it?

**Comment by mtk** [comment]
if i do a fresh checkout of VirtusLab/scala-cli and then a 'gh pr checkout 801', i see the new code.  do you know if i can add commits to the pull request from there?  i tried and it says i don't have the rights to your repo (your fork of the main repo)?

**Comment by asjad02** [comment]
@mtk  has given contributor rights

**Comment by romanowski** [comment]
Thank you @asjad02 and @mtk for your contribution! Since we are preparing migration to Scala 3 and we want to cut last release on Scala 2, I have decided to rebase and update slightly your PR and I did that in #818. I really wanted that changes in doctor  command are included in the upcoming release.

**Comment by mtk** [comment]
@romanowski i think you're saying you're cutting the the last version of scala-cli that will be built from scala v2, right?  and you want a version of our work in it?  if so, that's great.  but you should take the latest commit.  the duplicate-in-PATH check isn't correct in the version under #818 and i only discovered the correct natively-compiled check last night.  that will get you three correct checks while we continue to work on the others.

**Comment by mtk** [comment]
fyi, i'm talking about the version in fe78b539.

**Comment by romanowski** [comment]
@mtk I think best way would be to continue work directly from main, since pretty much all changes from this PR are already merged. As for detecting if native image is used, we picked a slightly [different property to check](https://github.com/VirtusLab/scala-cli/blob/main/modules/cli/src/main/scala/scala/cli/commands/Doctor.scala#L110)

**Comment by Gedochao** [comment]
It seems most of the changes from here  are already in the `main` branch (refer to #818).
https://github.com/VirtusLab/scala-cli/pull/818#issuecomment-1084793516 - some changes seem to still be missing, however.
relevant commit: https://github.com/VirtusLab/scala-cli/commit/45f546bee0af9ca98104dd12c0e8f9106e5f25c9
The relevant issue to track this: #698 
Closing this PR for now.

**Pull request closed without merging**
