### PR TITLE
fix: encode videos in yuv420p to support Firefox

### LINKED ISSUE #1685: Documentation video marked as corrupt on firefox
Not sure why, this seems to work correctly on chrome

https://scala-cli.virtuslab.org/img/scala-cli-getting-started-1.mp4

image

The console shows:

>Media resource https://scala-cli.virtuslab.org/img/scala-cli-getting-started-1.mp4 could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)
Details: auto mozilla::SupportChecker::AddMediaFormatChecker(const mozilla::TrackInfo &)::(anonymous class)::operator()() const: Decoder may not have the capability to handle the requested video format with YUV444 chroma subsampling.

Related post on mozilla support
https://support.mozilla.org/en-US/questions/1316956

### PR DESCRIPTION
**Pull request by danielleontiev**
Firefox does not support yuv444p format:
https://bugzilla.mozilla.org/show_bug.cgi?id=1368063

The suggested solution from the bug-tracker is to
reencode the video using ffmpeg -pix_fmt yuv420p option.

The following command was used:

ffmpeg -i old_video.mp4 -pix_fmt yuv420p out.mp4

Fixes #1685.

### CODE REVIEW

**Review by lwronski — APPROVED** [review]
@danielleontiev Thanks for your contribution - LGTM

**Comment by lwronski** [comment]
@danielleontiev  Your changes should be visible on website after the next release. After release of scala-cli we update our documentation.

**Comment by lwronski** [comment]
> @danielleontiev Thanks for your contribution - LGTM

@danielleontiev Can you verify if this changes fixed the problem?

**Comment by danielleontiev** [comment]
> @danielleontiev Can you verify if this changes fixed the problem?

Yes, I've tried just now and both videos works well for me in Firefox:

<details>
<summary>screenshots</summary>




</details>

**Comment by lwronski** [comment]
@danielleontiev It also works for me, so again thanks for your contribution.

**Pull request merged**
