### PR TITLE
move args definition to the top of the script

### LINKED ISSUE #1979: Script args in ".sc" files not visible in BSP clients
**Version(s)**
0.2.1

**Describe the bug**
In BSP editor clients such as IntelliJ and Metals, for some reason `args` is not visible in `.sc` files, even though both wrapper objects for the script are visible. e.g. in `words.sc`, `words` object and `words_sc` objects are visible. Also failing is `words.args`, but `words_sc.args$` is visible (however I believe `args$` is implementation detail right?).

**To Reproduce**
- in VS Code open a blank directory "script_args"
- create a script file "foo.sc"
- import the script with "Metals: Start Scala CLI BSP Server"

`args` does not appear as a method available in scope, therefore there are no completions and anything involving `args` is typed in the editor as `Nothing`.

**Expected behaviour**
I expect `args` to be available, typed as an `Array[String]` (does it have to be Array? anyway that's a different issue)

I also opened https://github.com/scalameta/metals/issues/5099, but I observe the same behaviour in IntelliJ.

### PR DESCRIPTION
**Pull request by bishabosha**
fixes https://github.com/VirtusLab/scala-cli/issues/1979

### CODE REVIEW

**Comment by lwronski** [comment]
> fixes #1979

I closed and reopened this PR in order to trigger the CI. It's weird, but the CI didn't start on the first time.

**Comment by bishabosha** [comment]
looks like only the stack trace comparisons are failing (line counts are now off by one in the expected stack trace)

**Comment by lwronski** [comment]
> looks like only the stack trace comparisons are failing (line counts are now off by one in the expected stack trace)

@bishabosha Can you update the expected lines in the stack traces in the tests? and then I would be happy to merge your changes

**Comment by bishabosha** [comment]
@lwronski should be ok now, could you cancel the CI for https://github.com/VirtusLab/scala-cli/commit/baa1fe11f2884b22be3f3bc398b47c993d46fc75?

**Comment by lwronski** [comment]
> @lwronski should be ok now, could you cancel the CI for [baa1fe1](https://github.com/VirtusLab/scala-cli/commit/baa1fe11f2884b22be3f3bc398b47c993d46fc75)?

I don't have to do it manually - the job was cancelled automatically. We used the  [cancel-in-progress](https://github.com/VirtusLab/scala-cli/blob/f86e7cd122c13852337ff8ec03ecc7155ea641cb/.github/workflows/ci.yml#L13). More info you can find [here](https://docs.github.com/en/enterprise-cloud@latest/actions/using-jobs/using-concurrency).

**Review by lwronski — APPROVED** [review]
LGTM. @bishabosha Thanks for your contribution.

**Pull request merged**
