### PR TITLE
Build CLI with Scala 2.13

### PR DESCRIPTION
**Pull request by alexarchambault**

### CODE REVIEW

**Review by romanowski — APPROVED** [review]

**Comment by lwronski** [comment]
I think, it should be also updated `scala` version in `scala-cli` dependency - [here](https://github.com/VirtusLab/scala-cli/blob/6de98417c8f98e9a9377391bdcb59797e5f8f2f6/modules/cli/src/main/scala/scala/cli/launcher/LauncherCli.scala#L14)

**Comment by alexarchambault** [comment]
(The CI error on Windows looks legit… I'd like to debug it locally on a Windows machine.)

**Comment by alexarchambault** [comment]
Includes https://github.com/VirtusLab/scala-cli/pull/689 as of now (should go away after a rebase once https://github.com/VirtusLab/scala-cli/pull/689 is merged).

**Comment by alexarchambault** [comment]
Still having one issue in 2.13: when verbosity is increased, we sometimes use [PPrint](https://github.com/com-lihaoyi/PPrint) to print stuff. In 2.13, PPrint [uses reflection](https://github.com/com-lihaoyi/PPrint/blob/3abeed80a4282f2c08768528eff7e24c07d05603/pprint/src-2.13/pprint/StringPrefix.scala#L4) to call `Iterable.collectionClassName`. From native images, this would require concrete `Iterable` classes to be added to the native-image reflection config to work fine, which is kind of a hassle. https://github.com/com-lihaoyi/PPrint/pull/80 should make PPrint not rely on reflection for that.

**Pull request merged**
