### PR TITLE
Tidy-up installation doc

### PR DESCRIPTION
**Pull request by lwronski**
Design installation page with clear installation section for beginners and more advanced installation.

### CODE REVIEW

**Comment by alexarchambault** [comment]
About the quick start, for Windows and macOS, I think it'd be better with either some kind of button, or a more explicit link. See how [docker](https://docs.docker.com/desktop/windows/install/) or [rustup](https://rustup.rs/#) do, for example.
Capture d’écran 2021-09-01 à 14 34 35
Capture d’écran 2021-09-01 à 14 34 59

**Comment by alexarchambault** [comment]
Maybe we could merge the "Advanced" and "OS-specific" sections too. We could have just "Advanced", with tabs such as
- Windows
  - Manual
  - Installer
  - choco? (soon)
  - nuget? (soon)
- macOS
  - Manual
  - Installer
  - brew
- Linux
  - Manual
  - apt
  - deb
  - yum
  - rpm
  - alpine
  - …

**Comment by bjornregnell** [comment]
> Maybe we could merge the "Advanced" and "OS-specific" sections too. We could have just "Advanced", with tabs such as

Sounds good. I'm not sure `manual` should be first in the list though. Perhaps in "popularity" order, I'd guess Installer first and then for Linux apt, deb, and perhaps manual last?

**Comment by bjornregnell** [comment]
On the other hand if it iis under "Advanced" having "Manual" first might be ok / better. Not sure.

**Review by alexarchambault — APPROVED** [review]

**Pull request merged**
