### PR TITLE
Add command to search for dependencies

### PR DESCRIPTION
**Pull request by andrelfpinto**
### Motivation
Scala CLI is all about being simple and intuitive while being powerful.
I am not a full time developer and many times I struggle to find the library I want to depend on.
For example, if I want to work with json, I know [Li Haoyi](https://github.com/lihaoyi) created a great (of many) library: ujson. But how can I depend on it? If I search the GitHub repositories of Li Haoyi, I need to know that ujson is inside [upickle](https://github.com/com-lihaoyi/upickle/). That is not very intuitive.
Well, we could also use [Scaladex](https://index.scala-lang.org/) and delve into the website, clicking our way through search and combo boxes until we find the library and the version. Then I can copy the dependency and paste into my file. That could be simpler.

### Solution
The solution I propose is to have a new command in `scala-cli` to `search` for the library:

```
> scala-cli search --query ujson --target JVM --scala-binary 3
Fetching from https://index.scala-lang.org/api/search?q=ujson&target=JVM&scalaVersion=3...
Found these artifacts:
1: com-lihaoyi/upickle
  ujson, ujson-argonaut, ujson-circe, ujson-js-2.11.11, ujson-js-2.12.4,
  ujson-json4s, ujson-jvm-2.11.11, ujson-jvm-2.12.4, ujson-play

Choose the repository:
```

Then you choose the repository:
```
Choose the repository: 1

Artifacts in com-lihaoyi/upickle:
1: ujson
2: ujson-argonaut
3: ujson-circe
4: ujson-js-2.11.11
5: ujson-js-2.12.4
6: ujson-json4s
7: ujson-jvm-2.11.11
8: ujson-jvm-2.12.4
9: ujson-play

Choose the artifact:
```

And finally the artifact:
```
Choose the artifact: 1
Fetching from https://index.scala-lang.org/api/project?organization=com-lihaoyi&repository=upickle&artifact=ujson&target=JVM&scalaVersion=3...

Use this import:
import $ivy.`com.lihaoyi:ujson_3:1.5.0`
```
Then you copy the dependency directly to you file.

I made a rough implementation and I would like to know if this is something that could make into Scala CLI. Of course, I am open to suggestions and to any kind of improvement of my code.

### CODE REVIEW

**Comment by romanowski** [comment]
Thank you @andrelfpinto for this contribution! 

Being able to search for dependencies is something that we really want to be a part of the Scala CLI but we are not sure what is the best way to implement that from the user experience point of view. We will experiment a bit and will come back to your PR.

**Comment by andrelfpinto** [comment]
Thank you, @romanowski, for your quick evaluation. Glad to hear that this functionality is in your plans. It seems Scala CLI is on its way to become an invaluable tool to promote Scala, especially to people new to it.

**Comment by SethTisue** [comment]
A recent discussion thread in this area: https://contributors.scala-lang.org/t/why-doesnt-scala-have-library-listing/5696

I agree it would be awesome if I could search Scaladex from the command line, and I think scala-cli is the right place for the functionality to live.

**Comment by Gedochao** [comment]
It seems we'll be taking another approach on implementing this feature.
The issue to track any future progress: https://github.com/VirtusLab/scala-cli/issues/1232
Closing this PR for now.

**Pull request closed without merging**
