### PR TITLE
Publish / publish setup tweaks

### PR DESCRIPTION
**Pull request by alexarchambault**
Things I tweaked / fixed for the demo of my Scalacon talk.

### CODE REVIEW

**Comment by alexarchambault** [comment]
Just checking what the CI says for now, I'll of course squash things, and maybe even split things in different PRs.

**Comment by alexarchambault** [comment]
About this PR: I've been wanting to write non regression tests for it, but I don't recall exactly which scenarios it's fixing. But from what I recall, it's definitely useful, and the publish command should have been written this way initially IMO. And as it doesn't break any existing test, my opinion is that it can be merged as is…

**Review by MaciejG604 — APPROVED** [review]
LGTM!

**Comment by MaciejG604** [comment]
The scenario you're fixing here is part of #1899 - artifacts won't get signed when secret keys are in config, and no warning will be presented to the user.
I will add tests for this in a follow up PR that will fully resolve #1899.

**Pull request merged**
