### PR TITLE
Quotation marks added to configuration example

### PR DESCRIPTION
**Pull request by Quafadas**
I believe the scala version must be enclosed in quotation marks.

This was a head scratcher for me - hoping it helps someone else.

### CODE REVIEW

**Comment by lwronski** [comment]
@Quafadas Thanks for contributing, can you change target branch to `stable`? Because documentation is generated from the `stable` branch.

Instead of specify url to png, can you attach png image to repo files?

**Comment by Quafadas** [comment]
Yes. Thankyou for the hint - bear with me on the PNG.

**Comment by lwronski** [comment]
and I have one suggestion, can you change branch base from `master` to `stable`? It would be great if you add only one your commit to `stable` branch.

Changes from the `master` are merged to `stable` only after release, so unreleased functionalities are not visible in the documentation.

I think, we need to create some contributing guide.

**Comment by Quafadas** [comment]
brb

**Pull request closed without merging**
