### PR TITLE
Update scalafmt-cli_2.13 to 3.7.16

### PR DESCRIPTION
**Pull request by MaciejG604**
## About this PR
📦 Updates [org.scalameta:scalafmt-cli_2.13](https://github.com/scalameta/scalafmt) from `3.7.15` to `3.7.16`

📜 [GitHub Release Notes](https://github.com/scalameta/scalafmt/releases/tag/v3.7.16) - [Version Diff](https://github.com/scalameta/scalafmt/compare/v3.7.15...v3.7.16)

## Usage
✅ **Please merge!**

I'll automatically update this PR to resolve conflicts as long as you don't change it yourself.

If you'd like to skip this version, you can just close this PR. If you have any feedback, just mention me in the comments below.

Configure Scala Steward for your repository with a [`.scala-steward.conf`](https://github.com/scala-steward-org/scala-steward/blob/b24a31f26085e546881e7c906abfd27de18134b6/docs/repo-specific-configuration.md) file.

_Have a fantastic day writing Scala!_

<details>
<summary>🔍 Files still referring to the old version number</summary>

The following files still refer to the old version number (3.7.15).
You might want to review and update them manually.
```
.scalafmt.conf
website/docs/release_notes.md
```
</details>
<details>
<summary>⚙ Adjust future updates</summary>

Add this to your `.scala-steward.conf` file to ignore future updates of this dependency:
```
updates.ignore = [ { groupId = "org.scalameta", artifactId = "scalafmt-cli_2.13" } ]
```
Or, add this to slow down future updates of this dependency:
```
dependencyOverrides = [{
  pullRequests = { frequency = "30 days" },
  dependency = { groupId = "org.scalameta", artifactId = "scalafmt-cli_2.13" }
}]
```
</details>

<sup>
labels: library-update, early-semver-patch, semver-spec-patch, old-version-remains, commit-count:n:2
</sup>

### CODE REVIEW

**Comment by tgodzik** [comment]
wasn't this version broken, though?

**Comment by MaciejG604** [comment]
No, why? [VirtusLab/scalafmt-native-image](https://github.com/VirtusLab/scalafmt-native-image) was unaffected by the recent repo and CI problems

Is the 3.7.16 of scalafmt itself broken?

**Comment by tgodzik** [comment]
I mean this one. https://github.com/scalameta/scalafmt/issues/3689

**Comment by MaciejG604** [comment]
Okay, didn't know that. Thanks for the heads-up!
So it seems we should wait for 3.7.17 before updating.

**Pull request closed without merging**
