### PR TITLE
Fix reference to macOS

### PR DESCRIPTION
**Pull request by kubukoz**

### CODE REVIEW

**Comment by alexarchambault** [comment]
@kubukoz Thanks! The messages you edited in your first commit actually originate from the sources, and `./mill generate-reference-doc.run` updates the `.md` files. I opened https://github.com/VirtuslabRnD/scala-cli/pull/118 to update the messages in the sources too.

**Comment by kubukoz** [comment]
doh, I now see this diff is +0 -0, guess that makes sense as the second commit reverted my only change 😂

Of course it's from the sources... I'll do it right later today.

**Comment by alexarchambault** [comment]
> Of course it's from the sources... I'll do it right later today.

https://github.com/VirtuslabRnD/scala-cli/pull/118 does it, I just merged it.

**Comment by kubukoz** [comment]
Thanks :)

**Pull request closed without merging**
