### PR TITLE
Set page size for aarch64 Linux binaries to 64k

### LINKED ISSUE #1714: Linux `aarch64` not working under Asahi Linux (Apple Silicon M1)
**Version(s)**
v0.1.19

**Describe the bug**
The Linux `aarch64` binary is not working under Asahi Linux (Apple Silicon M1), see below.

**To Reproduce**
1. Use Asahi Linux (https://asahilinux.org/) on a MacBook Pro M1 (it's basically just Arch Linux ARM)
1. Download https://github.com/VirtusLab/scala-cli/releases/download/v0.1.19/scala-cli-aarch64-pc-linux.gz
1. Extract the archive and `chmod 755 scala-cli-aarch64-pc-linux`
1. ```sh
    $ ./scala-cli-aarch64-pc-linux 
    Fatal error: Failed to create the main Isolate. (code 8)
    ```

**Expected behaviour**
The Linux `aarch64` binary should work.

### PR DESCRIPTION
**Pull request by mkurz**
Fixes #1714

Also see discussions here:
* https://github.com/coursier/coursier/issues/2636
* https://github.com/oracle/graal/pull/5605
* https://github.com/playframework/playframework/issues/11527#issuecomment-1363915402

### CODE REVIEW

**Review by lwronski — COMMENTED** [review]
@mkurz Thanks a lot for your contribution. I think we can merge it when you get the final confirmation from oracle - https://github.com/VirtusLab/scala-cli/issues/1714#issuecomment-1363927423.

**Comment by mkurz** [comment]
@lwronski It's official now! We have green light both from the GraalVM team (https://github.com/oracle/graal/pull/5605#issuecomment-1364006130) and from CI :wink: 
Please merge :+1:

**Comment by lwronski** [comment]
> @lwronski It's official now! We have green light both from the GraalVM team ([oracle/graal#5605 (comment)](https://github.com/oracle/graal/pull/5605#issuecomment-1364006130)) and from CI 😉
> Please merge 👍

@mkurz Now I'm thinking about page size. Should we use 64k size, maybe 16k will be enough? do you know any system that uses 64k? cc: @alexarchambault

**Comment by mkurz** [comment]
@lwronski Like said, I am not an expert in this field, just what I read on the internet now. For me it seems most Linux distributions come with 4kb page size kernels, and mine with 16k. It seems 64k is very unusual. It's up to you if you want to use 16k or 64k. If you use 16k, at least you know what the problem could be if someone comes up with a bug report that sounds like `Fatal error: Failed to create the main Isolate.`, in such a case you can still adjust the page size for an upcoming release then.

**Review by lwronski — APPROVED** [review]
LGTM, so let's merge this PR. Thanks for help!

**Pull request merged**
